### ISSUE TITLE
App crashes after configure page

### ISSUE THREAD

**Issue by rhysd** [rhysd/Chromenu#4]
## Environment

- Chromenu 0.1.4
- macOS 10.12

## Steps

1. Open app
2. Click '+' at header
3. Enter URL to first input form
4. Click 'OK'

## Error

<details>
<pre>
/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:222 Uncaught Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:431)
    at /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:446
    at EventEmitter.ipcMain.on.args (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:275)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368)
    at WebContents.emit (events.js:182)
exports.deserialize @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/error-utils.js:16
exception @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:222
metaToValue @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:226
exports.getGuestWebContents @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:338
proto.getWebContents @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:313
getMountedWebview @ footer.tsx:77
render @ footer.tsx:39
finishClassComponent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:14537
updateClassComponent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:14492
beginWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:15440
performUnitOfWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19108
workLoop @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19148
callCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:256
replayUnitOfWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:18374
renderRoot @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19264
performWorkOnRoot @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20138
performWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20050
performSyncWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20024
requestWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19893
scheduleWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19707
enqueueSetState @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:11141
Component.setState @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react/cjs/react.development.js:335
(anonymous) @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-redux/lib/components/Provider.js:65
dispatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/redux/lib/redux.js:220
Promise.all.then @ page_config.tsx:71
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
PageConfig.onSubmit @ page_config.tsx:60
callCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:270
executeDispatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:561
executeDispatchesInOrder @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:583
executeDispatchesAndRelease @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:688
forEachAccumulated @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:662
runEventsInBatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:816
runExtractedEventsInBatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:824
handleTopLevel @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4826
batchedUpdates$1 @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20235
batchedUpdates @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:2151
dispatchEvent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4905
(anonymous) @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20286
unstable_runWithPriority @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/scheduler/cjs/scheduler.development.js:255
interactiveUpdates$1 @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20285
interactiveUpdates @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:2170
dispatchInteractiveEvent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4882
/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16913 The above error occurred in the <Footer> component:
    in Footer
    in div
    in Unknown (created by Context.Consumer)
    in Connect(Component)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16913
logError @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16949
update.callback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:17861
callCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16229
commitUpdateEffects @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16268
commitUpdateQueue @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:16259
commitLifeCycles @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:17179
commitAllLifeCycles @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:18532
callCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:256
commitRoot @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:18744
(anonymous) @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20214
unstable_runWithPriority @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/scheduler/cjs/scheduler.development.js:255
completeRoot @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20213
performWorkOnRoot @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20142
performWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20050
performSyncWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20024
requestWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19893
scheduleWork @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:19707
enqueueSetState @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:11141
Component.setState @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react/cjs/react.development.js:335
(anonymous) @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-redux/lib/components/Provider.js:65
dispatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/redux/lib/redux.js:220
Promise.all.then @ page_config.tsx:71
_tickCallback @ internal/process/next_tick.js:68
Promise.then (async)
PageConfig.onSubmit @ page_config.tsx:60
callCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:149
invokeGuardedCallbackDev @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:199
invokeGuardedCallback @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:270
executeDispatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:561
executeDispatchesInOrder @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:583
executeDispatchesAndRelease @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:688
forEachAccumulated @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:662
runEventsInBatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:816
runExtractedEventsInBatch @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:824
handleTopLevel @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4826
batchedUpdates$1 @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20235
batchedUpdates @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:2151
dispatchEvent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4905
(anonymous) @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20286
unstable_runWithPriority @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/scheduler/cjs/scheduler.development.js:255
interactiveUpdates$1 @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:20285
interactiveUpdates @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:2170
dispatchInteractiveEvent @ /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/react-dom/cjs/react-dom.development.js:4882
internal/process/next_tick.js:68 Uncaught (in promise) Error: Invalid guestInstanceId: null
    at Object.getGuestForWebContents (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:431)
    at /Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:446
    at EventEmitter.ipcMain.on.args (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:275)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (/Users/rhysd/Develop/github.com/rhysd/Chromenu/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:368)
    at WebContents.emit (events.js:182)
</pre>
</details>

---

CC: @brpaz

**Comment by rhysd** [comment]
After some investigation, I found this line was causing the error.

https://github.com/rhysd/Chromenu/blob/b8c300688f689071d618500592247b417e7ce379/renderer/components/footer.tsx#L77

**Comment by rhysd** [comment]
I guess this is a timing issue since timing of rendering components to DOM was changed in newer React. I assumed the `WebContents` has already been created here, but it seems that the assumption looks no longer correct.

**Comment by brpaz** [comment]
Any chance to fix this issue?

**Comment by rhysd** [comment]
Currently I have no extra resource to allocate to this project. It requires investigation across Electron framerwork and React. And it crashes in Electron framework so we might need to raise an issue to Electron. Trying the latest Electron v5 may solve this.

**Comment by rhysd** [comment]
Thanks to #5, this seemed to be fixed.
